### ISSUE TITLE
Thanks IsQianGe...but what do I do now

### ISSUE THREAD

**Issue by shabysheik** [Seeed-Studio/pxt-grove#21]
I can see your code in the link that takes me to the github site, but what do I do with that. I'm not a super user of Github, so it is new to me. I do appreciate your efforts though :-)

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/pxt-grove/releases/tag/v0.4.0

**Comment by Pillar1989** [comment]
@shabysheik  you can use the lastest code now.
