### ISSUE TITLE
Memory error if used with Bluetooth

### ISSUE THREAD

**Issue by microbit-carlos** [Seeed-Studio/pxt-grove#3]
Steps to reproduce:
* Go to makecode.microbit.org
* Create a new project
* Add the "grove" package
* Add the "bluetooth" package
* Download program
* Flash program to micro:bit

The micro:bit will then inmediatly crash with error 020 - no free memory: https://makecode.microbit.org/device/error-codes

Hex file showing issue: [microbit-grove-bluetooth.hex.zip](https://github.com/Seeed-Studio/pxt-grove/files/1899434/microbit-grove-bluetooth.hex.zip)

Would it be possible to reduce the memory footprint to allow the use of this package with Bluetooth?

**Comment by Pillar1989** [comment]
We have updated the relevant code. Please try again. If there is any problem, you can open the issue again
