### ISSUE TITLE
Problems with Grove Joystick

### ISSUE THREAD

**Issue by simube** [Seeed-Studio/pxt-grove#30]
Hi

Searching for how to use the Thumb Joystick with grove i stumbled over this repository:
https://github.com/Microbit-Grove-Library/pxt-ThumbJoystick

Seems that this code was implemented to this repo here, but is not mentioned in the readme-file.

I modified a cable to make the Joystick work, but now, I‘m not able to choose a direction in the block. (See screenshot) No other extensions are installed.

![81580017-EEEC-4686-B733-818C7CE1FB35](https://user-images.githubusercontent.com/7550745/147753413-745d1296-1a90-44a1-a5f7-182bdec5ab83.jpeg)

**Comment by baorepo** [comment]
Thank you very much for your interest in the Grove Joystick module and also the reference library that you have implemented. Great work!

Currently, we do not have enough resources to produce a fully supported library.
