### ISSUE TITLE
Ultrasonic Ranger and 4-digit display counters not working

### ISSUE THREAD

**Issue by humb1t** [Seeed-Studio/pxt-grove#34]
When I try to use 
- Ultrasonic Sensor (in cm) at P0
- set Display to 4-digit Display at P0 and P14
I receive an error in make code:Property 'C16' does not exist on type 'typeof DigitalPin'". Here is an example:
 
https://makecode.microbit.org/_Hqtgx99XbKde

**Comment by martinwork** [comment]
Reported in Micro:bit Foundation support ticket https://support.microbit.org/helpdesk/tickets/84361 (private)

@MKleinSB @MatthewJeffson This extension seems to have been changed (https://github.com/Seeed-Studio/pxt-grove/commit/d0ead22b5bf1a3e782a659fe804278ee2e1ab5f7) to target calliopemini.

https://github.com/Seeed-Studio/pxt-grove/blob/39b14d543c5e62f372033c04d55a77ea970249aa/pxt.json#L23

Is it possible to restore micro:bit compatibility?

**Comment by Lesords** [comment]
Please change C16 to P0 and try again

**Comment by humb1t** [comment]
@Lesords please check the template I shared. I do not choose C16 there, I choose P0.

**Comment by Lesords** [comment]
> [@Lesords](https://github.com/Lesords) please check the template I shared. I do not choose C16 there, I choose P0.

I just looked at this template.

Click JavaScript button, then you will see C16 in line 8, just change it

**Comment by Lesords** [comment]
> > [@Lesords](https://github.com/Lesords) please check the template I shared. I do not choose C16 there, I choose P0.
> 
> I just looked at this template.
> 
> Click JavaScript button, then you will see C16 in line 8, just change it

Or you can reselect P0

**Comment by humb1t** [comment]
@Lesords thank you, I regret that I didn't check Javascript tab to see that. It seems like by default the settings in blocks view are different from what is really encoded in them. I will close that issue then.

**Comment by martinwork** [comment]
Thanks @MKleinSB for proposing a fix: https://github.com/Seeed-Studio/pxt-grove/pull/35

Thanks @Lesords for suggesting the workaround.

When the block is added on https://makecode.microbit.org/ it says P0 so it's not obvious to a micro:bit user what the C17 message is about.

![image](https://github.com/user-attachments/assets/40d6a65c-be00-494a-9a15-f820cff912c2)

C16 and C17 are default pin selections in the extension code that are not appropriate for micro:bit
https://github.com/Seeed-Studio/pxt-grove/blob/39b14d543c5e62f372033c04d55a77ea970249aa/main.ts#L524
https://github.com/Seeed-Studio/pxt-grove/blob/39b14d543c5e62f372033c04d55a77ea970249aa/main.ts#L588

**Comment by martinwork** [comment]
Reported in Micro:bit Educational Foundation support ticket https://support.microbit.org/helpdesk/tickets/84830 (private)

@humb1t @MKleinSB Could we reopen this until #35 is merged?

**Comment by humb1t** [comment]
Sure, let me do that.

**Comment by Lesords** [comment]
My bad, I have merged #35 and released a new release

So I have to close this issue again (

Feel free to re-open it if you have any other questions

**Comment by martinwork** [comment]
@Lesords @humb1t @MKleinSB Thanks everyone!
