### ISSUE TITLE
v0.2.0 Release?

### ISSUE THREAD

**Issue by FranklinWhale** [Seeed-Studio/pxt-grove#4]
I notice that the incompatibility between micro:bit v1 and grove extension v0.1.0 has been fixed in 1154cb2fefe75305fd10c111b8f103c468e46118. The change appears backward compatible with micro:bit v0. May I know when v0.2.0 with the fix will be released? Thanks.

**Comment by FranklinWhale** [comment]
I think the new release should include fixes for #5

**Comment by microbit-mark** [comment]
Please run a pxt-bump for this release @WayenWeng

**Comment by Pillar1989** [comment]
We have updated the relevant code. Please try again. If there is any problem, you can open the issue again
