### ISSUE TITLE
Move to Math.idiv

### ISSUE THREAD

**Issue by pelikhan** [Seeed-Studio/pxt-grove#5]
The new version of MakeCode introduces floating point arithmetic. This is a breaking change that requires a fix in your sources: replace existing division, eg. ``x / y`` by ``Math.idiv(x, y)``.

* https://github.com/Seeed-Studio/pxt-grove/blob/master/main.ts#L113

**Comment by pelikhan** [comment]
* https://github.com/Seeed-Studio/pxt-grove/blob/master/main.ts#L140

**Comment by abchatra** [comment]
MakeCode for the micro:bit update is coming soon. Part of the update is floating point support. Existing MakeCode website supports only integer division which means
1/2 = 0
With this update 1/2 = 0.5

__Action for you:__
We have automatically detected this package uses division operator. Please take one of the following actions
- If the change to floating point division doesn't matter you can ignore and close this issue.
- If you want integer division then update your package typescript code to use integer division. Change  _a/b_ to  _Math.idiv(a, b)_

You can test your package on the update here: https://makecode.microbit.org/beta

All the details on the update: https://makecode.com/blog/microbit/v1-beta

div found in main.ts

**Comment by Pillar1989** [comment]
We have updated the relevant code. Please try again. If there is any problem, you can open the issue again
